# Site settings
title: Towards Serenity - Help for depression and suicide
description: "A blog for sharing thoughts on technology, science and insights at TheReviewIndex."
url: "http://towards-serenity.github.io/"
ogimage: "img/default-ogimage.png"
author:
  name: "Towards Serenity"
  email: "towards.serenity@yahoo.com"
  url: "https://depression-suicide.org"


# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
